---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: demo
  labels:
    app: http-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
        - name: nginx-hello
          image: nginxdemos/hello:0.2
          ports:
            - containerPort: 80
